// ─────────────────────────────────────────────────────────────
//  Story 3.2 – AI-Powered Lead Matching & Scoring Engine
//  Types & Interfaces
// ─────────────────────────────────────────────────────────────

/** Raw lead profile as extracted by the scraper worker (Story 3.1) */
export interface LeadProfile {
  /** Internal lead UUID from the `leads` table */
  id: string;

  /** LinkedIn canonical URL – used as the dedup key */
  linkedin_url: string;

  full_name: string;

  /** Raw job title string scraped from the profile headline */
  job_title: string;

  /** Current company name */
  company: string;

  /** Approximate headcount band scraped or enriched */
  company_headcount?: string; // e.g. "11-50", "51-200"

  /** Industry tag as shown on the LinkedIn profile */
  industry?: string;

  /** Geographic location string as shown on LinkedIn */
  location?: string;

  /** Full "About" bio text – richest signal for LLM scoring */
  bio?: string;

  /** Any additional key-value metadata stored in the JSONB `metadata` column */
  metadata?: Record<string, unknown>;
}

/** Workspace-level Ideal Customer Profile definition */
export interface ICPCriteria {
  /** Target seniority / function titles – partial matches are rewarded */
  target_titles: string[]; // e.g. ["Founder", "VP of Sales", "CEO", "Head of Growth"]

  /** Target industries */
  target_industries: string[]; // e.g. ["SaaS", "Information Technology", "B2B Software"]

  /** Acceptable headcount band */
  company_headcount: {
    min: number; // e.g. 11
    max: number; // e.g. 500
  };

  /** Target geographies – city, region, or country strings */
  target_locations: string[]; // e.g. ["Pune", "San Francisco", "India"]

  /**
   * Free-text description of the ideal customer written by the workspace admin.
   * This is sent verbatim to the LLM for semantic comparison.
   * e.g. "B2B SaaS founders who are actively scaling a sales team and looking
   *       to automate outbound lead generation."
   */
  icp_description: string;

  /**
   * Leads scoring below this threshold are automatically dropped
   * from the active campaign pool (enforced by the caller).
   */
  minimum_score_threshold: number; // 0–100, e.g. 75
}

/** Result produced by the scoring engine for a single lead */
export interface ScoredLead {
  /** Mirrors the input lead */
  lead: LeadProfile;

  /** Final composite ICP fitness score 0–100 */
  icp_score: number;

  /** Whether the lead clears the workspace minimum threshold */
  passes_threshold: boolean;

  /** Concise, human-readable rationale generated by the LLM */
  score_rationale: string;

  /** Granular sub-scores for observability / debugging */
  sub_scores: {
    title_match: number;      // 0–25
    industry_match: number;   // 0–20
    location_match: number;   // 0–15
    headcount_match: number;  // 0–15
    semantic_bio: number;     // 0–25 (LLM-driven)
  };
}

/** Batch result returned after processing an entire lead list */
export interface BatchScoringResult {
  /** All leads that scored >= minimum_score_threshold */
  qualified_leads: ScoredLead[];

  /** All leads dropped due to low score */
  disqualified_leads: ScoredLead[];

  /** Summary stats for logging / analytics */
  summary: {
    total_processed: number;
    total_qualified: number;
    total_disqualified: number;
    average_score: number;
    processing_time_ms: number;
  };
}

/** Shape of the JSON block the LLM must return */
export interface LLMScoringResponse {
  semantic_score: number; // 0–25
  rationale: string;      // ≤ 3 sentences
}
